### ISSUE TITLE
Support CommonJS modules

### ISSUE THREAD

**Issue by ahmsec** [Short-io/otm-detector#1]
Currently otm-detector only supports ES Modules, and not CommonJS. The module cannot be imported via `require()`. This makes the package incompatible with certain codebases. Would it be possible to support CommonJS?

**Comment by gugu** [comment]
Does Node.js 22 --experimental-require-module option solve this problem?

I'll merge PR, which adds commonjs support to ESM version if this module

**Comment by ahmsec** [comment]
The `--experimental-require-module` flag might solve the problem (unsure), but that may not be an option on a complex pre-existing codebase, as that may have other undesired side effects.

**Comment by ahmsec** [comment]
@gugu Thanks for merging! Could you push the latest version to NPM as well?

**Comment by ahmsec** [comment]
@gugu Also - I just saw your https://github.com/Short-io/otm-detector/commit/3bb7a4152ac56a9ce4878552a0f67b493ab84e09 commit, which does `require('./blocklist.js')` from the `.cjs` file. I'm not sure if that would work since `blocklist.js` uses ESM exports?  It may be better to keep the `.cjs` file only be auto-generated by `rollup` with no manual edits (if not already).

**Comment by gugu** [comment]
Yes, it was a mistake
