### ISSUE TITLE
Please add kuku.lu MX records

### ISSUE THREAD

**Issue by ahmsec** [Short-io/otm-detector#4]
The disposable domains provided by https://m.kuku.lu/en.php are using the following MX domains. Could you please add them to the blocklist?

```
recv6.erinn.biz
recv7.erinn.biz
recv8.erinn.biz
recv1.erinn.biz
recv100.erinn.biz
recv101.erinn.biz
recv2.erinn.biz
recv3.erinn.biz
recv4.erinn.biz
```

To validate, try running `dig mx haren.uk` or on any other of their domains.

**Comment by gugu** [comment]
👍🏻  released a new version
