### ISSUE TITLE
Clarify that the blocklist does not just include "one-time mail services"

### ISSUE THREAD

**Issue by BitesizedLion** [Short-io/otm-detector#5]
I think it would be good if the README clarifies that the blocklist does not just include "one-time mail services" but also email forwarding, aliases and other services that aren't actually "one-time mail" services

Such as forwardemail.net, simplelogin.co, Namecheap's jellyfish and Cloudflare.

**Comment by gugu** [comment]
I've added FAQ section to the module with purpose and clarifications. Email forwarding and aliasing is not the reason for addition to the list
